# Configuration/Services.yaml
services:
  Webzadev\Hisnulmuslim\:
    resource: '../Classes/*'
    autowire: true
    autoconfigure: true
  Webzadev\Hisnulmuslim\Controller\ApiController:
    public: true
